name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'action-surefire-report/**'
  pull_request:
    paths-ignore:
      - 'action-surefire-report/**'

permissions: {}

jobs:
  build:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: |
            block-commits/package-lock.json
            github-app-token/package-lock.json
            slash-command-dispatch/package-lock.json

      - name: Build and test block-commits
        working-directory: block-commits
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Build and test github-app-token
        working-directory: github-app-token
        run: |
          npm ci
          npm run build

      - name: Build and test slash-command-dispatch
        working-directory: slash-command-dispatch
        run: |
          npm ci
          npm run build
          npm run format-check
          npm run lint
          npm run test

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol github-app-token/dist/ | wc -l)" -gt "0" ] ||
             [ "$(git diff --ignore-space-at-eol slash-command-dispatch/dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff
